# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: K-MUG DEVCON 2015
email: info@k-mug.org
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://devcon2016.k-mug.org" # the base hostname & protocol for your site
twitter_username: k_mug
github_username:  k-mug

# Build settings
markdown: kramdown
